/** @type {import("stylelint").Config} */
export default {
    extends: ["stylelint-config-standard-scss"],

    // Generated by `npm run build:icons` (utils/build-icon-font.mjs) — a compact
    // one-rule-per-line glyph map that is not hand-edited, and is excluded from
    // Prettier for the same reason. Linting it would only report on the
    // generator's output style.
    ignoreFiles: ["scss/abstracts/_icons.scss"],

    // WHAT THIS GATE IS FOR
    //
    // Prettier already owns the whitespace of every `.scss` file in the tree.
    // stylelint is here for the checks Prettier structurally cannot perform
    // (#1622): invalid declarations, unknown properties and units, duplicate
    // and dead selectors, and — the reason it matters most — the naming
    // conventions that `kb/dev-docs/concepts/css-architecture.md` documents as
    // an extension surface third-party modules compile against.
    //
    // So the rule set is deliberately narrow in one specific way: every rule
    // that only says "spell this the other way" is off. Those are a second
    // formatter's taste, they would fire ~170 times across 52 hand-written
    // partials whose output is byte-identical either way, and satisfying them
    // is exactly the cosmetic refactor this repository forbids. Every rule that
    // can tell you something is *wrong* stays on.
    rules: {
        // ── Conventions this repository actually documents ──────────────────

        // BEM under the `.sohl` namespace (css-architecture §3):
        // `block__element--modifier`, kebab-case within each part, and no
        // redundant `sohl-` prefix (the wrapper supplies the namespace). The
        // same pattern has to admit the Foundry-owned classes SoHL *selects on*
        // (`window-content`, `form-group`, `flexrow`) — they are plain
        // kebab-case blocks, so they fit without a carve-out. Third-party
        // classes that do not (ProseMirror's) are disabled at the one site
        // rather than widened into the pattern.
        "selector-class-pattern": [
            "^[a-z][a-z0-9]*(-[a-z0-9]+)*(__[a-z0-9]+(-[a-z0-9]+)*)?(--[a-z0-9]+(-[a-z0-9]+)*)?$",
            {
                message:
                    "Expected class selector to be BEM kebab-case: block__element--modifier (kb/dev-docs/concepts/css-architecture.md §3)",
            },
        ],

        // Design tokens are the runtime extension surface (css-architecture §4):
        // module authors re-skin SoHL by overriding `--sohl-*`, so a token
        // renamed or misnamed here is an API break with nothing else guarding
        // it. Globally the rule enforces *shape* — lowercase kebab-case — which
        // is all it can enforce everywhere, because it inspects `var()`
        // references as well as declarations, and SoHL legitimately reads
        // Foundry-core properties (`--font-size-12`, `--form-field-height`,
        // `--color-scheme`) and its own inline layout hooks set from templates
        // (`--ledger-cols`, `--array-cols`, `--hp-fill`).
        //
        // The `--sohl-*` namespace itself is enforced where the tokens are
        // actually declared — `scss/abstracts/`, whose `emit-tokens` mixin is
        // the single source that §4 names. See the `overrides` block below.
        "custom-property-pattern": [
            "^[a-z][a-z0-9]*(-[a-z0-9]+)*$",
            {
                message:
                    "Expected custom property to be lowercase kebab-case (kb/dev-docs/concepts/css-architecture.md §4)",
            },
        ],

        // ── Off: blank-line placement ───────────────────────────────────────
        //
        // Prettier deliberately preserves author blank lines rather than
        // normalising them, so these rules are not a Prettier conflict — they
        // are a *second* formatter's opinion about the same bytes, and the only
        // way to satisfy them is to reflow 79 sites across the tree.
        "at-rule-empty-line-before": null,
        "rule-empty-line-before": null,
        "declaration-empty-line-before": null,
        "custom-property-empty-line-before": null,
        "comment-empty-line-before": null,
        "scss/double-slash-comment-empty-line-before": null,
        "scss/dollar-variable-empty-line-before": null,

        // ── Off: comment shape ──────────────────────────────────────────────
        //
        // Every partial's header comment separates paragraphs with a bare `//`
        // line, and this rule counts each one as an empty comment (58 of them).
        // The convention is the repository's, and it is worth more than the
        // rule.
        "scss/comment-no-empty": null,

        // ── Off: notation preference ────────────────────────────────────────
        //
        // Each of these rewrites a value into an equivalent spelling —
        // `rgba(0 0 0 / 0.5)` for `rgba(0, 0, 0, 0.5)`, `currentcolor` for
        // `currentColor`, `flex-flow` for `flex-direction` + `flex-wrap`. The
        // compiled CSS is the same either way, so the rule can only ever report
        // taste, never a defect.
        "alpha-value-notation": null,
        "color-function-notation": null,
        "color-function-alias-notation": null,
        "value-keyword-case": null,
        "font-family-name-quotes": null,
        "declaration-block-no-redundant-longhand-properties": null,
        "shorthand-property-no-redundant-values": null,
        "scss/at-if-no-null": null,
    },

    overrides: [
        {
            // `abstracts/` is where SoHL's design tokens are declared — the
            // `emit-tokens` mixin in `_tokens.scss` renders every `--sohl-*`
            // custom property from the SCSS maps (css-architecture §4). That is
            // the runtime surface module authors build against, so here the
            // pattern is the namespace itself, not just its shape: a token
            // written straight into this folder has to be `--sohl-…`, and a
            // `var()` in it may only read one.
            //
            // Know its limit. The generated names are built by interpolation
            // (`--sohl-color-#{$name}`), which is not standard syntax, so
            // stylelint skips those declarations entirely — this rule cannot see
            // the map-driven tokens, only hand-written ones. Renaming a map key
            // silently renames a public token and no linter here will say so.
            files: ["scss/abstracts/**/*.scss"],
            rules: {
                "custom-property-pattern": [
                    "^sohl-[a-z0-9]+(-[a-z0-9]+)*$",
                    {
                        message:
                            "Expected custom property to be in the --sohl-* token namespace (kb/dev-docs/concepts/css-architecture.md §4)",
                    },
                ],
            },
        },
    ],
};
